Equipe.create!([
  {name: "Barcelone", pays: "Espagne", entraineur: "Luis Enrique", statsgenerale: 93, nombreJoueurs: 13, joueurs_count: 0, image_file_name: "fcbarca.png", image_content_type: "image/png", image_file_size: 10263, image_updated_at: "2017-03-16 22:23:09"},
  {name: "Marseille", pays: "France", entraineur: "Rudi Garcia", statsgenerale: 74, nombreJoueurs: nil, joueurs_count: 0, image_file_name: "om.jpg", image_content_type: "image/jpeg", image_file_size: 48234, image_updated_at: "2017-03-23 18:19:55"},
  {name: "Juventus", pays: "Italie", entraineur: "Massimiliano Allegri", statsgenerale: 82, nombreJoueurs: nil, joueurs_count: 0, image_file_name: "juventus.png", image_content_type: "image/png", image_file_size: 185408, image_updated_at: "2017-03-23 18:23:59"},
  {name: "Real Madrid", pays: "Espagne", entraineur: "Zinédine Zidane", statsgenerale: 93, nombreJoueurs: nil, joueurs_count: 0, image_file_name: "real.png", image_content_type: "image/png", image_file_size: 105228, image_updated_at: "2017-03-23 18:25:47"},
  {name: "SuperStars", pays: "Inconnu", entraineur: "Inconnu", statsgenerale: 100, nombreJoueurs: nil, joueurs_count: 0, image_file_name: "superstar.png", image_content_type: "image/png", image_file_size: 71145, image_updated_at: "2017-03-23 18:27:22"},
  {name: "Chelsea", pays: "Angleterre", entraineur: "Antonio Conte", statsgenerale: 89, nombreJoueurs: nil, joueurs_count: 0, image_file_name: "chel_logo.png", image_content_type: "image/png", image_file_size: 79632, image_updated_at: "2017-03-23 18:31:51"},
  {name: "Manchester United", pays: "Angleterre", entraineur: "José Mourinho", statsgenerale: 85, nombreJoueurs: nil, joueurs_count: 0, image_file_name: "man.png", image_content_type: "image/png", image_file_size: 410438, image_updated_at: "2017-03-23 18:34:49"},
  {name: "Bayern Munich", pays: "Allemagne", entraineur: "Carlo Ancelotti", statsgenerale: 91, nombreJoueurs: nil, joueurs_count: 0, image_file_name: "bayern.png", image_content_type: "image/png", image_file_size: 15262, image_updated_at: "2017-03-23 18:35:44"}
])
Joueur.create!([
  {statsgenerale: 94, poste: "ATT", club: "Barcelone", nationalite: "Argentine", name: "Messi", pac: 89, dri: 87, tir: 89, def: 85, pas: 87, phy: 84, qualite: "BUTEUR", equipe_id: 1, image_file_name: "messi-custom_(1).png", image_content_type: "image/png", image_file_size: 97440, image_updated_at: "2017-03-16 22:07:29", user_id: 1, equipe_perso_id: 2, prix: 15000, estAchete: true},
  {statsgenerale: nil, poste: "", club: "Barcelone", nationalite: "", name: "Neymar", pac: 92, dri: 96, tir: 87, def: 32, pas: 82, phy: 67, qualite: "SNIPER", equipe_id: 1, image_file_name: "neymar-custom.png", image_content_type: "image/png", image_file_size: 87341, image_updated_at: "2017-03-16 21:55:27", user_id: nil, equipe_perso_id: nil, prix: 13000, estAchete: true},
  {statsgenerale: nil, poste: "", club: "", nationalite: "", name: "Iniesta", pac: nil, dri: nil, tir: nil, def: nil, pas: nil, phy: nil, qualite: "", equipe_id: 1, image_file_name: "iniesta-custom.png", image_content_type: "image/png", image_file_size: 95728, image_updated_at: "2017-03-16 22:09:19", user_id: nil, equipe_perso_id: nil, prix: 9000, estAchete: false},
  {statsgenerale: 88, poste: "MIL", club: "Manchester United", nationalite: "France", name: "Pogba", pac: 77, dri: 87, tir: 80, def: 72, pas: 83, phy: 87, qualite: "", equipe_id: 10, image_file_name: "pogba-custom.png", image_content_type: "image/png", image_file_size: 95776, image_updated_at: "2017-03-18 13:23:47", user_id: nil, equipe_perso_id: nil, prix: 9500, estAchete: true},
  {statsgenerale: 90, poste: "ATT", club: "Manchester United", nationalite: "Suède", name: "Z. Ibrahimović", pac: 76, dri: 92, tir: 90, def: 45, pas: 91, phy: 94, qualite: "FINISHER", equipe_id: 10, image_file_name: "zlatan-custom.png", image_content_type: "image/png", image_file_size: 96201, image_updated_at: "2017-03-18 13:29:03", user_id: nil, equipe_perso_id: nil, prix: 8500, estAchete: true},
  {statsgenerale: 93, poste: "MIL", club: "Chelsea", nationalite: "Belgique", name: "Hazard", pac: 93, dri: 96, tir: 91, def: 42, pas: 91, phy: 75, qualite: "DEADEYE", equipe_id: 9, image_file_name: "hazard-custom.png", image_content_type: "image/png", image_file_size: 94611, image_updated_at: "2017-03-18 13:33:57", user_id: nil, equipe_perso_id: nil, prix: 11000, estAchete: true},
  {statsgenerale: 89, poste: "MIL", club: "Atlético Madrid", nationalite: "France", name: "Griezmann", pac: 87, dri: 89, tir: 88, def: 34, pas: 82, phy: 71, qualite: "HAWK", equipe_id: nil, image_file_name: "griez-custom.png", image_content_type: "image/png", image_file_size: 94700, image_updated_at: "2017-03-18 13:37:28", user_id: nil, equipe_perso_id: nil, prix: 8900, estAchete: false},
  {statsgenerale: 88, poste: "MDC", club: "Legend", nationalite: "France", name: "P. Viera", pac: 84, dri: 82, tir: 71, def: 85, pas: 79, phy: 91, qualite: "MAESTRO", equipe_id: 8, image_file_name: "vieira-custom.png", image_content_type: "image/png", image_file_size: 89014, image_updated_at: "2017-03-19 15:11:21", user_id: nil, equipe_perso_id: nil, prix: 200000, estAchete: true},
  {statsgenerale: 87, poste: "ATT", club: "???", nationalite: "Italie", name: "Balotelli", pac: 74, dri: 78, tir: 54, def: 87, pas: 89, phy: 88, qualite: "AAAAAAH", equipe_id: nil, image_file_name: "balotelli-custom.png", image_content_type: "image/png", image_file_size: 94747, image_updated_at: "2017-03-23 14:55:33", user_id: nil, equipe_perso_id: nil, prix: 5000, estAchete: false},
  {statsgenerale: nil, poste: "", club: "", nationalite: "", name: "Pikachu", pac: nil, dri: nil, tir: nil, def: nil, pas: nil, phy: nil, qualite: "", equipe_id: 8, image_file_name: "pikachu-custom.png", image_content_type: "image/png", image_file_size: 92163, image_updated_at: "2017-03-23 13:25:24", user_id: nil, equipe_perso_id: nil, prix: 1000000, estAchete: false},
  {statsgenerale: 100, poste: "", club: "Legend", nationalite: "France", name: "Remi", pac: nil, dri: nil, tir: nil, def: nil, pas: nil, phy: nil, qualite: "", equipe_id: 8, image_file_name: "remi-custom.png", image_content_type: "image/png", image_file_size: 92241, image_updated_at: "2017-03-23 13:36:00", user_id: nil, equipe_perso_id: nil, prix: 80000, estAchete: false},
  {statsgenerale: 85, poste: "MIL", club: "CHelsea", nationalite: "France", name: "Kante", pac: nil, dri: nil, tir: nil, def: nil, pas: nil, phy: nil, qualite: "", equipe_id: 9, image_file_name: "kante-custom.png", image_content_type: "image/png", image_file_size: 92753, image_updated_at: "2017-03-23 13:48:12", user_id: nil, equipe_perso_id: nil, prix: 7900, estAchete: false}
])

